# Generated by Django 3.0.7 on 2020-06-15 06:42

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Sin especificar')], max_length=1, verbose_name='Sexo')),
                ('age', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Edad')),
                ('financial_goals', models.BooleanField(default=False, verbose_name='Indica si cuentas con metas financieras:')),
                ('savings', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Ahorro aproximado')),
                ('investment_knowledge', models.BooleanField(verbose_name='Indica si cuentas con conocimientos sobre inversiones')),
            ],
            options={
                'verbose_name': 'Encuesta',
                'verbose_name_plural': 'Encuestas',
                'ordering': ['-id'],
            },
        ),
    ]
